config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'

  get '/caesars' => 'caesars#index'
  get '/caesars/new' => 'caesars#new'
  post '/caesars/new' => 'caesars#create'

  resources :caesars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caesar.rb
class Caesar < ApplicationRecord

  def cipher(message, key)
    key = key.to_i % 26
    self.key = key
    self.message = message
    p self.key, self.message
    code = String.new
    message.split("").each do |character|
      if character.match(/[A-Z]/)
        if character.ord + key > 90
          changed = (character.ord  - 26) + key
          code << changed.chr
        elsif character.ord + key < 65
          changed = (character.ord + 26) + key
          code << changed.chr
        else
          changed = character.ord + key
          code << changed.chr
        end
      elsif character.match(/[a-z]/)
        if character.ord + key > 122
          changed = (character.ord - 26) + key
          code << changed.chr
        elsif character.ord + key < 97
          changed = (character.ord + 26) + key
          code << changed.chr
        else
          changed = character.ord + key
          code << changed.chr
        end
      else
        code << character  
      end
    end
      self.code = code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/caesars_controller.rb
class CaesarsController < ApplicationController
  before_action :set_caesar, only: [:show, :edit, :update, :destroy]

  # GET /caesars
  # GET /caesars.json
  def index
    @caesars = Caesar.all
  end

  # GET /caesars/1
  # GET /caesars/1.json
  def show
    @caesar = Caesar.find(params[:id])
  end

  # GET /caesars/new
  def new
    @caesar = Caesar.new
  end

  # GET /caesars/1/edit
  def edit
  end

  # POST /caesars
  # POST /caesars.json
  def create
    @caesar = Caesar.new(caesar_params)
    @caesar.cipher(params[:caesars][:message], params[:caesars][:key])
      
    if @caesar.save
      redirect_to @caesar
    else
      render :new
    end
  end

  # PATCH/PUT /caesars/1
  # PATCH/PUT /caesars/1.json
  def update
    respond_to do |format|
      if @caesar.update(caesar_params)
        format.html { redirect_to @caesar, notice: 'Caesar was successfully updated.' }
        format.json { render :show, status: :ok, location: @caesar }
      else
        format.html { render :edit }
        format.json { render json: @caesar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caesars/1
  # DELETE /caesars/1.json
  def destroy
    @caesar.destroy
    respond_to do |format|
      format.html { redirect_to caesars_url, notice: 'Caesar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caesar
      @caesar = Caesar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caesar_params
      params.fetch(:caesar, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caesars_helper.rb
module CaesarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/caesars/edit.html.erb
<h1>Editing Caesar</h1>

<%= render 'form', caesar: @caesar %>

<%= link_to 'Show', @caesar %> |
<%= link_to 'Back', caesars_path %>

app/views/caesars/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caesar Cipher</title>
</head>
<body>

<h1>Caesar Ciphers</h1>

<h3><%= link_to 'New Caesar Cipher', new_caesar_path %></h3>

<table>
  <thead>
    <tr>
      <td>Original Message</td>
      <td>Cipher Key</td>
      <td>Coded Message</td>
    </tr>
  </thead>

  <tbody>
    <% @caesars.each do |caesar| %>
      <tr>
        <td><%= caesar.message %></td>
        <td><%= caesar.key %></td>
        <td><%= caesar.code %></td>
        <td><%= link_to 'Show', caesar %></td>
        <td><%= link_to 'Edit', edit_caesar_path(caesar) %></td>
        <td><%= link_to 'Destroy', caesar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</body>
</html>

app/views/caesars/new.html.erb
<%= form_for :caesars do |f| %>

  <%= f.label :message %>
  <%= f.text_field :message %>
  <%= f.label :key %>
  <%= f.number_field :key %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', caesars_path %>

app/views/caesars/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <td>Original Message</td>
      <td>Cipher Key</td>
      <td>Coded Message</td>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @caesar.message %></td>
        <td><%= @caesar.key %></td>
        <td><%= @caesar.code %></td>
      </tr>
  </tbody>
</table>>

<%= link_to 'Edit', edit_caesar_path(@caesar) %> |
<%= link_to 'Back', caesars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGames</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1> Ruby Games Homepage</h1>
<p>Stuff goes here</p>